UPDATE BLC_FLD_DEF SET FRIENDLY_NAME='内容' WHERE FLD_DEF_ID = 2;
UPDATE BLC_FLD_DEF SET FRIENDLY_NAME='标题' WHERE FLD_DEF_ID = 3;
UPDATE BLC_FLD_DEF SET FRIENDLY_NAME='图片' WHERE FLD_DEF_ID = 7;
UPDATE BLC_FLD_DEF SET FRIENDLY_NAME='目标链接' WHERE FLD_DEF_ID = 8;
UPDATE BLC_FLD_DEF SET FRIENDLY_NAME='消息文本' WHERE FLD_DEF_ID = 9;
UPDATE BLC_FLD_DEF SET FRIENDLY_NAME='HTML内容' WHERE FLD_DEF_ID = 10;


UPDATE BLC_FLD_GROUP SET NAME = '内容' WHERE FLD_GROUP_ID=1;
UPDATE BLC_FLD_GROUP SET NAME = '广告字段' WHERE FLD_GROUP_ID=4;
UPDATE BLC_FLD_GROUP SET NAME = 'HTML 字段' WHERE FLD_GROUP_ID=5;
UPDATE BLC_FLD_GROUP SET NAME = '消息字段' WHERE FLD_GROUP_ID=6;